# Utiliser une image Node.js légère
FROM node:20-slim

# Définir le dossier de travail dans le conteneur
WORKDIR /usr/src/app

# Installer les dépendances nécessaires (procps pour `ps`, etc.)

RUN apt-get update \
 && apt-get install -y --no-install-recommends procps \
 && rm -rf /var/lib/apt/lists/*
 
# Copier uniquement les fichiers de dépendances pour installer plus vite
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'app (enlever . .)
COPY . .

# Exposer le port utilisé par NestJS
EXPOSE 3000

# Lancer l'app en mode développement avec hot-reload
CMD ["npm", "run", "start:dev"]
