services:
  db:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecodeli
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio
    restart: always
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_REGION_NAME: gra
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

#Volumes
volumes:
  db:
    driver: local
  minio_storage: {}
